name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-arm64]
        compiler: [msvc, mingw]
    env:
      WH_MODELS_DIR: ${{ runner.temp }}\wh_models
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bootstrap toolchain
        shell: pwsh
        run: ./bootstrap.ps1

      - name: Derive model cache key
        id: modelkey
        shell: pwsh
        run: |
          $content = Get-Content -Raw ui/wh/ModelManager.cs
          $m = [regex]::Match($content, 'DefaultModelFileName\s*=>\s*"([^"]+)"')
          if (-not $m.Success) { throw 'Could not parse DefaultModelFileName from ModelManager.cs' }
          $name = $m.Groups[1].Value
          echo "model_name=$name" >> $env:GITHUB_OUTPUT

      - name: Restore model cache
        uses: actions/cache@v4
        with:
          path: ${{ env.WH_MODELS_DIR }}
          key: wh-models-${{ steps.modelkey.outputs.model_name }}

      - name: Build
        shell: pwsh
        run: ./build.ps1 -Compiler ${{ matrix.compiler }}

      - name: E2E UI test
        shell: pwsh
        run: ./test.ps1 -TimeoutSeconds 120
