name: CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-arm64]
        compiler: [msvc, mingw]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bootstrap toolchain
        shell: pwsh
        run: |
          ./bootstrap.ps1

      - name: Build (${{ matrix.compiler }})
        shell: pwsh
        run: |
          $arch = if ($env:PROCESSOR_ARCHITECTURE -eq 'ARM64') { 'arm64' } else { 'x64' }
          ./build.ps1 -Compiler ${{ matrix.compiler }} -Arch $arch -Configuration Release

      - name: Test
        shell: pwsh
        run: |
          ./test.ps1

